apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: geonode
  namespace: argocd
spec:
  project: default
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    # repoURL: https://github.com/StatCan/charts/tree/master/stable/geoserver
    # repoURL: https://statcan.github.io/charts
    repoURL: https://ktjaco.github.io/charts
    chart: geonode
    targetRevision: 0.1.2
    helm:
      values: |
        image:
          registry: docker.io
          repository: geonode/geonode
          tag: 3.1
        ingress:
          enabled: false
        hosts:
        - host: chart-example.local
          paths: []
        resources:
          limits:
            cpu: "4"
            memory: 8Gi
          requests:
            cpu: "4"
            memory: 8Gi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
