apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: geoserver
  namespace: argocd
spec:
  project: default
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    # repoURL: https://github.com/StatCan/charts/tree/master/stable/geoserver
    repoURL: https://statcan.github.io/charts
    chart: geoserver
    targetRevision: 0.0.1
    helm:
      values: |
        image:
          registry: docker.io
          repository: kartoza/geoserver
          tag: 2.18.2
        ingress:
          enabled: false
	  hosts:
	    - host: chart-example.local
              paths: []
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
