apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pycsw
  namespace: argocd
spec:
  project: default
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://ktjaco.github.io/helm-charts
    chart: pycsw
    targetRevision: 0.0.1
    helm:
      values: |
        image:
          registry: docker.io
          repository: postgis/postgis
          tag: 12-3.1
        ingress:
          enabled: false
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: "2"
            memory: 4Gi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
